[package]
name = "claims-meta"
version = "2.0.0"
edition = "2021"
publish = false
authors = ["Ovidiu Damian - Itheum"]

[dev-dependencies]
[dependencies.claims]
path = ".."

[dependencies.multiversx-sc]
version = "0.39.5"

[dependencies.multiversx-sc-meta]
version = "0.39.5"
