[package]
name = "claims-meta"
version = "2.0.1"
edition = "2021"
publish = false
authors = ["Ovidiu Damian - Itheum"]

[dev-dependencies]
[dependencies.claims]
path = ".."

[dependencies.multiversx-sc]
version = "0.45.1"

[dependencies.multiversx-sc-meta]
version = "0.45.1"
