// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           20
// Async Callback (empty):               1
// Total number of exported functions:  22

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    claims
    (
        init => init
        setClaimToken => set_claim_token
        pause => pause
        unpause => unpause
        addPrivilegedAddress => add_privileged_address
        removePrivilegedAddress => remove_privileged_address
        addDepositorAddress => add_depositor_address
        removeDepositorAddress => remove_depositor_address
        addClaim => add_claim
        addClaims => add_claims
        removeClaim => remove_claim
        removeClaims => remove_claims
        claim => harvest_claim
        viewTokenIdentifier => claim_token
        viewClaim => claim
        viewClaimModifyDate => claim_modify_date
        isPaused => is_paused
        viewPrivilegedAddresses => privileged_addresses
        viewDepositorAddresses => depositor_addresses
        viewClaims => view_claims
        viewClaimWithDate => view_claims_with_date
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
